#
#server:
#  port: ${server.port}
#  tomcat:
#    max-connections: ${server.tomcat.max-connections}
#    accept-count: ${server.tomcat.accept-count}
#    threads:
#      max: ${server.tomcat.threads.max}
#
#management:
#  health:
#    rabbit:
#      enabled: ${management.health.rabbit.enabled}
#
#spring:
#  application:
#    name: ${spring.application.name}
#  profiles:
#    active: dev
#  datasource:
#    driver-class-name: ${spring.datasource.driver-class-name}
#    url: ${spring.datasource.url}
#    username: ${spring.datasource.username}
#    password: ${spring.datasource.password}
#  sql:
#    init:
#      mode: ${spring.sql.init.mode}
#  rabbitmq:
#    host: ${spring.rabbitmq.host}
#    port: ${spring.rabbitmq.port}
#    username: ${spring.rabbitmq.username}
#    password: ${spring.rabbitmq.password}
#    virtual-host: ${spring.rabbitmq.virtual-host}
#  jackson:
#    default-property-inclusion: ${spring.jackson.default-property-inclusion}
#  data:
#    redis:
#      host: ${spring.data.redis.host}
#      port: ${spring.data.redis.port}
#      password: ${spring.data.redis.password}
#      lettuce:
#        pool:
#          max-active: ${spring.data.redis.lettuce.pool.max-active}
#          max-idle: ${spring.data.redis.lettuce.pool.max-idle}
#          min-idle: ${spring.data.redis.lettuce.pool.min-idle}
#          time-between-eviction-runs: ${spring.data.redis.lettuce.pool.time-between-eviction-runs}
#mybatis-plus:
#  type-aliases-package: ${mybatis-plus.type-aliases-package}
#
#logging:
#  level:
#    com.hmdp: ${logging.level.com.hmdp}
#    org.springframework.data.redis: ${logging.level.org.springframework.data.redis}
#
#debug: ${debug}

spring:
  profiles:
    active: prod
  application:
    name: hmdp
  ai:
    chat:
      client:
      ##允许多个模型，每个模型都有自己的配置
        enabled: false
    ##下面是阿里巴巴的配置
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      enabled: true
      
      chat:
        model: qwen-plus-2025-07-28
        api-base: https://ws-mhs2k50uiwwwvefx.cn-beijing.maas.aliyuncs.com/compatible-mode/v1
        memory:
          repository:
            jdbc:
              initialize-schema: always
              platform: mariadb

logging:
  level:
    com.hmdp: WARN                            # 其他 hmdp 包安静
    com.hmdp.service.impl: DEBUG              # 想看 AuthServiceImpl 日志
    com.hmdp.interceptor: DEBUG               # 想看 Token 拦截器日志
    com.hmdp.controller: WARN                 # Controller 按需调
    org.springframework.data.redis: WARN
    com.hmdp.config: debug
    com.hmdp.permission: debug
    com.hmdp.agent: DEBUG
    com.hmdp.agent.tool: DEBUG
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true