---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ntwitm.
--- DateTime: 2026/2/14 21:36
---
--强制清除相关token
local tokenKey = KEYS[1]
local refreshKey = KEYS[2]
local versionKey = KEYS[3]

local newToken = ARGV[1]
local refreshToken = ARGV[2]
local version = tonumber(ARGV[3])
local tokenExpireSeconds = tonumber(ARGV[4])
local refreshExpireSeconds = tonumber(ARGV[5])
local versionExpireSeconds = tonumber(ARGV[6])

-- 直接删除旧的（单设备登录，直接踢下线）
redis.call('DEL', tokenKey)
redis.call('DEL', refreshKey)
redis.call('DEL', versionKey)

-- 设置新的
redis.call('SET', tokenKey, newToken, 'EX', tokenExpireSeconds)
redis.call('SET', refreshKey, refreshToken, 'EX', refreshExpireSeconds)
redis.call('SET', versionKey, version, 'EX', versionExpireSeconds)

return '{"code":1,"message":"success"}'