---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ntwitm.
--- DateTime: 2026/2/13 16:59
---
local voucherId =ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]
local stockKey ='seckill:stock:'..voucherId
local orderKey = 'seckill:order:'..voucherId
if (tonumber(redis.call('get',stockKey)) <= 0) then
    --库存不足
    return 1
end
if (redis.call("sismember",orderKey,userId) == 1) then
    --缓存存在，不可重复下单
    return 2
end
--自减然后存入redis
redis.call("incrby",stockKey,-1)
redis.call("sadd",orderKey,userId)
return 0
