---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ntwitm.
--- DateTime: 2026/2/13 23:16
---
-- KEYS[1]: RefreshToken = "login:token:" .. userId

-- ARGV[1]: oldRefreshToken (请求携带的 RefreshToken)
-- ARGV[2]: newRefreshToken (新生成的 RefreshToken)
-- ARGV[3]: expireSeconds (新 RefreshToken 的过期秒数，例如 30*60 = 1800)
-- ARGV[4]: newToken (新生成的token)
--ARGV[5]: tokenExpireSeconds 外部生成token的指定过期时间

local RefreshTokenKey = KEYS[1]
local tokenKey = KEYS[2]
local oldRefreshToken = ARGV[1]
local newRefreshToken = ARGV[2]
local refreshTokenExpireSeconds = tonumber(ARGV[3])
local newToken =ARGV[4]
local tokenExpireSeconds = ARGV[5]
local exists = redis.call('EXISTS', RefreshTokenKey)
if exists == 0 then
    return '{"code":0,"message":"RefreshToken key not found"}'
end
local storedToken = redis.call('GET', RefreshTokenKey)
if storedToken ~= oldRefreshToken then
    return '{"code":0,"message":"RefreshToken mismatch"}'
end
redis.call('DEL', RefreshTokenKey)
redis.call('SET', RefreshTokenKey, newRefreshToken, 'EX', refreshTokenExpireSeconds)
redis.call('DEL',tokenKey)
redis.call('SET',tokenKey,newToken,'EX',tokenExpireSeconds)
return '{"code":1,"message":"success","data":{"newToken":"' .. newToken .. '","newRefreshToken":"' .. newRefreshToken .. '"}}'